version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/app
    restart: always
    command: bash -c "npm install && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/survey-api
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo